### ISSUE TITLE
Unable update CRASHED connection

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-stagetimerio-api#17]
If the module fails to connect to the stagetimer server, the module loops and it is not possible to correct the login data.

RECONSTRUCTION:
1. go to CONNECTIONS tab
2. create and configure the connection to Stagetimer.io so that it works correctly on the first try.
3. delete the room in stagetimer.
4. the connection loops and hangs. Cannot change room ID or other details.

ENVIROMENT:
Stagetimer.io website
Windows 11
Chrome last version

**Comment by lhermann** [comment]
On it.

Boy does Companion not forgive an uncaught error 😅

**Comment by lhermann** [comment]
@Suenee I was not able to reproduce the issue in the way you described (but found and fixed another bug in the process).

Can you share your DEBUG logs?
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/64d7300c-e22e-4630-881a-2c6cb873788b">

**Comment by Suenee** [comment]
> system: ** Connection started **
> Starting up module class: Ft
> Sentry disabled
> Module-host accepted registration
> error: Bad configuration! Please review module settings and try again.
> error: Trace: Init failed: Error: Failed to start. Error: Invalid URL
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:290266
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210491
> error: Failed to init: Error: Failed to start. Error: Invalid URL Error: Failed to start. Error: Invalid URL
>     at Ft.configure (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:405913)
>     at Ft.init (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:397123)
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:290202
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210330
>     at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:209377)
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210537
>     at new Promise (<anonymous>)
>     at t.default.add (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210180)
>     at Ft._handleInit (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:289646)
>     at t.IpcWrapper.receivedMessage (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:274236)
> system: ** Connection stopped **
> system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js" **
> system: ** Connection started **
> Starting up module class: Ft
> Sentry disabled
> Module-host accepted registration
> error: Bad configuration! Please review module settings and try again.
> error: Trace: Init failed: Error: Failed to start. Error: Invalid URL
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:290266
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210491
> error: Failed to init: Error: Failed to start. Error: Invalid URL Error: Failed to start. Error: Invalid URL
>     at Ft.configure (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:405913)
>     at Ft.init (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:397123)
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:290202
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210330
>     at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:209377)
>     at C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210537
>     at new Promise (<anonymous>)
>     at t.default.add (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:210180)
>     at Ft._handleInit (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:289646)
>     at t.IpcWrapper.receivedMessage (C:\Program Files\Companion\resources\bundled-modules\stagetimerio-api\main.js:2:274236)
> system: ** Connection stopped **

... etc. in never ending cycle....

**Comment by lhermann** [comment]
It says `Error: Invalid URL`. Do you mind sharing your module configuration settings as well?

**Comment by Suenee** [comment]
> It says `Error: Invalid URL`. Do you mind sharing your module configuration settings as well?

Yes, sure. It was configured and worked well. Then we made upgrade from 2.* to 3,1 companion and it crashed as you see....

**Comment by lhermann** [comment]
I see, thank you for the screenshot.
Between Companion v2 and v3 there were some major changes from the companion side. I assume it may have something to do with that.
Can you try adding a second instance of the module under a different name and see if the problem persists?

**Comment by Suenee** [comment]
> I see, thank you for the screenshot. Between Companion v2 and v3 there were some major changes from the companion side. I assume it may have something to do with that.
> 
> 1. Can you try adding a second instance of the module under a different name and see if the problem persists?
> 2. Can you try the latest beta `3.4.0+7122-main-3bc10380` and see if it persists there?

ad 1. yes, it will works fine. Do you have an idea how to swap the connections and do not lost buttons settings?
ad 2. it is production computer of my client. I can not test there *BETA. sorry. :-(

![image](https://github.com/user-attachments/assets/0932fb94-0d95-43dc-948a-14c1778ede95)

**Comment by Suenee** [comment]
> It says `Error: Invalid URL`. Do you mind sharing your module configuration settings as well?

Maybe it is about your upgrade API url?

**Comment by lhermann** [comment]
Unfortunately I don't know if it's possible to reset a module configuration or edit it outside the GUI.
I've asked on the Companion Slack. But you may get a faster answer if you ask there directly.

**Comment by lhermann** [comment]
But I think I know where this error is created, so I may fix it to handle invalid values and not crash in the future.

**Comment by Suenee** [comment]
> Unfortunately I don't know if it's possible to reset a module configuration or edit it outside the GUI. I've asked on the Companion Slack. But you may get a faster answer if you ask there directly.

I am not on Slack at the moment registered. Thx for your QA to Companion team.

> But I think I know where this error is created, so I may fix it to handle invalid values and not crash in the future.
It would be nice...

Thank you for both... :)

**Comment by lhermann** [comment]
@Suenee 
1. Click the Companion icon in the menu bar/ taskbar and go to “show config folder”.
2. Go into the folder of your installed version (probably `v3.1`)
3. Open the file `db` in a text editor.
4. Search for `"label":"stagetimer"`
5. In the vicinity you'll find the config values. Here you can edit them, then save the file, then start Companion again.

**Comment by Suenee** [comment]
Here you can download all db.
[db.zip](https://github.com/user-attachments/files/16323720/db.zip)
